/// Flutter icons Pramuka
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pramuka
///      fonts:
///       - asset: fonts/Pramuka.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Pramuka {
  Pramuka._();

  static const _kFontFam = 'Pramuka';
  static const String? _kFontPkg = null;

  static const IconData pancasila =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kelapa =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
